version: '3.7'

services:
  wordle-dev:
    container_name: wordle-dev
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ".:/app:z"
    ports:
      - 3000:3000
        #environment:
        #- CHOKIDAR_USEPOLLING=true
